### ISSUE TITLE
shorter version of the connection labels

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/models#35]
for html output (and maybe more), need shorter version of the connection labels
   examples:
    protocol: TCP src-ports: 1-442,444-65535 dst-ports: 443 - shorten to TCP src-ports: 1-442,444-65535 dst-ports: 443
    protocol: TCP src-ports: 442; protocol TCP dst-ports: 443 - shorten to TCP src-ports: 442; TCP dst-ports: 443
    protocol: TCP src-ports: 443 - shorten to TCP src-ports: 443
    protocol: TCP dst-ports: 443 - shorten to TCP 443
    protocol: TCP dst-ports: 443-449,722 - shorten to TCP 443-449,722

**Comment by haim-kermany** [comment]
need examples also with icmp-type and icmp-code

**Comment by zivnevo** [comment]
`protocol: ICMP icmp-type: 0 icmp-code: 0` - shorten to `ICMP type: 0 code: 0`

**Comment by zivnevo** [comment]
See also [this issue](https://github.com/np-guard/vpc-network-config-analyzer/issues/360)
